apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-application
  namespace: argocd # must be in a valid source ns as defined in the ArgoCD project
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cooervo/kubernetes-examples.git
    targetRevision: HEAD
    path: 7-argocd-app-of-apps/apps/example-app/
  destination:
    server: https://kubernetes.default.svc
