apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/custom-apps/status/ 

namespace: status

commonLabels:
  env: prod

patchesStrategicMerge:
  - deployment.yaml