---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-app
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cooervo/kubernetes-examples.git
    targetRevision: HEAD
    path: 7-argocd-app-of-apps/apps/status-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true