apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    targetRevision: dev
    helm:
      valueFiles:
        # helm.valuesFiles path is relative to spec.source.path of base template
        - ../../values/argocd/dev.values.yaml