apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deployment-dev.yaml
# args needs special treatment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "dev app running 🙂👍"
  target:
    kind: Deployment
- path: service-dev.yaml