annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: v1.11.4
description: Kubernetes Pod Security Standards implemented as Kyverno policies
home: https://kyverno.io/policies/
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
keywords:
- kubernetes
- nirmata
- policy agent
- validating webhook
- admissions controller
kubeVersion: '>=1.16.0-0'
maintainers:
- email: cncf-kyverno-maintainers@lists.cncf.io
  name: kyverno-maintainers
name: kyverno-policies
sources:
- https://github.com/kyverno/policies
type: application
version: 3.1.4
