apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example-app-auto-scaler
  namespace: example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-app
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80