apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: default
spec:
  # rate SecretManager pulls GCPSM, Low refereshInternval for demo purpose,
  # Set this value based on your requirement to limit the number of API calls to GCP Secret Manager.
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    # name of the ClusterSecretStore (or kind specified)
    name: my-gcp-secret-store
  target:
    # name of the k8s Secret to be created
    name: eso-demo-credential    
    creationPolicy: Owner
  data:
  - secretKey: name
    remoteRef:
      # name of the GCPSM secret key
      key: eso-demo      