apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-application
  namespace: argocd # must be in a valid source ns as defined in the ArgoCD project
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  # Source using istio/istiod helm chart
  # equivalent for: helm install istiod istio/istiod -n istio-system --wait
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    helm:
      wait: true
    targetRevision: 1.20.0
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 2
