apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-app
  labels:
    app: status-app
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: status-app
  template:
    metadata:
      labels:
        app: status-app
    spec:
      containers:
        - image: busybox:1.36.1
          name: busybox-httpd
          args:
            - |
              mkdir -p /www && \
              echo "${MESSAGE}" > /www/index.html && \
              httpd -f -p 0.0.0.0:${PORT} -h /www
          command:
            - /bin/sh
            - -c
          env:
            - name: PORT
              value: "80"
            - name: MESSAGE
              value: "ok"
          ports:
            - containerPort: 80

