apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: status-app
  namespace: status
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: status-app
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80