apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- status-app.yaml

commonLabels:
  appType: custom # custom apps + resources, basically everything that is not a helm chart