apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: argocd # must be in a valid source ns as defined in the ArgoCD project
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    targetRevision: v1.14.4
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
