kind: Service
apiVersion: v1
metadata:
  name: backend-api
  labels:
    service: backend-api
spec:
  selector:
    # serving the backend-api deployment
    app: backend-api
  type: ClusterIP # ClusterIP is only accessible within the cluster
  ports:
    - port: 3000
      targetPort: 3000
      name: http
