apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-application
  namespace: argocd # must be in a valid source ns as defined in the ArgoCD project
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  # Source using helm charts 
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istio/base
    helm:
      parameters:
        - name: defaultRevision
          value: "default"
    targetRevision: v1.20.0
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
