apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: status-app-auto-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: status-app
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80