apiVersion: v1
kind: Service
metadata:
  name: app-load-balancer
  labels:
    service: app-load-balancer
spec:
  selector:
    app: frontend-app
  type: LoadBalancer
  ports:
    - port: 5001
      name: http # needed due to Anthos Service Mesh: https://cloud.google.com/service-mesh/docs/naming-service-ports