apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: workload-identity-tutorial@winter-field-401115.iam.gserviceaccount.com
  name: k8s-service-account
  namespace: default
