apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: workload-identity-tutorial@winter-field-401115.iam.gserviceaccount.com
  name: workload-identity-user
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    name: node
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      serviceAccountName: k8s-service-account
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: node
          image: europe-west6-docker.pkg.dev/winter-field-401115/artifact-repository-qa/pytorch:v1.5 # UPDATE w/ your image
      restartPolicy: Always
